version: '3'

services: 

  app: 
    build: 
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
    networks:
      - app-network
    tty: true
    ports: 
      - "8080:8080"
    restart: on-failure
    depends_on: 
      - mysql

  mysql: 
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=favorecidoapi
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports: 
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    networks: 
      - app-network
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - "app-network"

networks: 
  app-network:
    driver: bridge